### ISSUE TITLE
Able to build standard, but not modified rdkit - Apple Silicon - fatal error: 'boost/detail/endian.hpp' file not found

### ISSUE THREAD

**Issue by JHucker** [connorcoley/ochem_predict_nn#14]
Running the below in my terminal successfully builds the standard rdkit within a conda environment:

```
export ENV_NAME=ochem_predict_nn
conda create -n $ENV_NAME -y python=3.8 anaconda
conda activate $ENV_NAME
conda install -y numpy matplotlib cmake cairo pillow \
  eigen pkg-config boost-cpp boost py-boost pip
yes | pip install yapf==0.11.1 coverage==3.7.1

# git clone https://github.com/connorcoley/rdkit
git clone https://github.com/rdkit/rdkit
cd rdkit && mkdir build && cd build

export PYROOT=/Users/jacobhucker/anaconda3/envs/$ENV_NAME
export CFLAGS="-Wno-implicit-function-declaration"

cmake -D PYTHON_INCLUDE_DIR=$PYROOT/include/python3.8 \
  -D RDK_BUILD_AVALON_SUPPORT=ON \
  -D RDK_BUILD_CAIRO_SUPPORT=ON \
  -D RDK_BUILD_INCHI_SUPPORT=ON \
  -D Boost_INCLUDE_DIR=$PYROOT/include \
  -D PYTHON_EXECUTABLE=$PYROOT/bin/python3.8 \
  -D Boost_NO_SYSTEM_PATHS=ON \
  -D Boost_NO_BOOST_CMAKE=ON \
  -D RDK_INSTALL_INTREE=OFF \
  -D CMAKE_INSTALL_PREFIX=$PYROOT \
  ..

make && make install && make clean
```

However, repeating the same using the modified rdkit version yields the following warning/s upon running cmake:

```
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   Alignment
   AvalonLib
   Catalogs
   ...
   Subgraphs
   SubstructMatch
   Trajectory
   avalon_clib
   hc
```

Then, the following error upon running make:

```
[  1%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/BitVect.cpp.o
In file included from /Users/jacobhucker/projects/ochem_predict_nn/rdkit/Code/DataStructs/BitVect.cpp:14:
/Users/jacobhucker/projects/ochem_predict_nn/rdkit/Code/RDGeneral/StreamOps.h:21:10: fatal error: 'boost/detail/endian.hpp' file not found
#include <boost/detail/endian.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [Code/DataStructs/CMakeFiles/DataStructs.dir/BitVect.cpp.o] Error 1
make[1]: *** [Code/DataStructs/CMakeFiles/DataStructs.dir/all] Error 2
make: *** [all] Error 2
```

Appreciate any assistance here, I'm not experienced with building from source -- please let me know if any other information would be useful.

**Comment by bxs0906** [comment]
Hello, have you installed custom keras?
I want to communicate with you

**Comment by brndnsy** [comment]
I fixed this - you need to open the cpp files in question and change the deprecated imports.

**Comment by bxs0906** [comment]
I will try it.
Thank you for the reply.&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Brandon Charles"; 
Date: 2021年8月10日(星期二) 晚上7:06
To: "connorcoley/ochem_predict_nn"; 
Cc: "白晓森"; "Comment"; 
Subject: Re: [connorcoley/ochem_predict_nn] Able to build standard, but not modified rdkit - Apple Silicon - fatal error: 'boost/detail/endian.hpp' file not found (#14)

&nbsp;


 
I fixed this - you need to open the cpp files in question and change the deprecated imports.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brndnsy** [comment]
You're welcome, I remember dealing with this[ endian.hpp](https://github.com/boostorg/endian/issues/45#issuecomment-664760174) error, as well as a numpy one. By the way, I'm working on Ubuntu 20.04 on an M1 MacBook using Parallels Desktop. 

This is an example of changing the import in StreamOps.h. 

![image](https://user-images.githubusercontent.com/41188975/128858968-4c1c0355-baaa-4f9c-a7ba-98257389f2da.png)

Refs: https://www.boost.org/doc/libs/1_72_0/boost/predef/detail/endian_compat.h 
https://www.rdkit.org/docs/cppapi/StreamOps_8h_source.html

**Comment by brndnsy** [comment]
This is how I fixed the numpy import, in the file DataStructs.cpp. I had to update the code to work with the latest versions of keras and tensorflow as the older versions aren't available for the M1. 

![image](https://user-images.githubusercontent.com/41188975/128859574-cec4d603-4aa0-4717-b7b9-f60049a4d941.png)

**Comment by JHucker** [comment]
Very late back to this, but, this has solved it for me. Thank you so much for your help @brndnsy!

**Comment by chetanpandey1266** [comment]
> You're welcome, I remember dealing with this[ endian.hpp](https://github.com/boostorg/endian/issues/45#issuecomment-664760174) error, as well as a numpy one. By the way, I'm working on Ubuntu 20.04 on an M1 MacBook using Parallels Desktop.
> 
> This is an example of changing the import in StreamOps.h.
> 
> ![image](https://user-images.githubusercontent.com/41188975/128858968-4c1c0355-baaa-4f9c-a7ba-98257389f2da.png)
> 
> Refs: https://www.boost.org/doc/libs/1_72_0/boost/predef/detail/endian_compat.h https://www.rdkit.org/docs/cppapi/StreamOps_8h_source.html

I tried replacing the import but now its showing: unable to determine system endianness

![image](https://github.com/connorcoley/ochem_predict_nn/assets/55939332/54ca15a6-bd80-4326-b81d-6f696a515552)


```
I got the solution:
I have to change BOOST_BIG_ENDIAN to BOOST_ENDIAN_BIG_BYTE 
and BOOST_LITTLE_ENDIAN to BOOST_ENDIAN_LITTLE_BYTE

```
