### ISSUE TITLE
can't run generate_candidates_edits_fullgrants.py

### ISSUE THREAD

**Issue by zgong99** [connorcoley/ochem_predict_nn#5]
Great work! I'm trying to reproduce the work in my computer.
When I run this python script, it gives me the following wrong message. In the README, you suggested using a modified rdkit from https://github.com/connorcoley/rdkit. But how to install it into python? for example, anconda?

python  data/generate_candidates_edits_fullgrants.py
---------------------------------
Out of 140583 database templates,
Loaded 1704 templates
Sorted by count, descending
Checked completed entries
17422 done IDs found
16686 unique reactant smiles found
#########
#########
Number of reactant atoms: 45
Reactants w/o map: Cc1cc(O)cc(C)c1CC(NC(=O)OC(C)(C)C)C(=O)N(C(C)C)C(C)c1nc(-c2ccccc2)c[nH]1.O=C(O)C(F)(F)F
Reactants w/ map: [CH3:1][c:2]1[cH:3][c:4]([OH:5])[cH:6][c:7]([CH3:8])[c:9]1[CH2:10][CH:11]([NH:12][C:13](=[O:14])[O:15][C:16]([CH3:17])([CH3:18])[CH3:19])[C:20](=[O:21])[N:22]([CH:23]([CH3:24])[CH3:25])[CH:26]([CH3:27])[c:28]1[n:29][c:30](-[c:31]2[cH:32][cH:33][cH:34][cH:35][cH:36]2)[cH:37][nH:38]1.[O:39]=[C:40]([OH:41])[C:42]([F:43])([F:44])[F:45]
  0%|                                                                                                                                                                | 0/1704 [00:00<?, ?it/s]
Error!! 'molAtomMapNumber'

**Comment by connorcoley** [comment]
Hi @zgong99 ,

You will have to build the modified RDKit from source, unfortunately. See here: https://www.rdkit.org/docs/Install.html#building-from-source

**Comment by zgong99** [comment]
I have installed the modified RDKit from source, it works now. thanks a lot!

**Comment by connorcoley** [comment]
Great!
