### ISSUE TITLE
how to run scripts/lowe_interactive_predict.py?

### ISSUE THREAD

**Issue by ZZP12** [connorcoley/ochem_predict_nn#6]
Very impressive work!
I tried to run the already-trained model, but I got: 
```
File "ochem_predict_nn/data/generate_candidates_edits_fullgrants.py", line 3, in <module>
    from global_config import USE_STEREOCHEMISTRY
ImportError: No module named global_config
```
If I moved the `global_config.py` from `ochem_predict_nn` to `scripts`, and reran the command, I got:
```
  import ochem_predict_nn.main.transformer as transformer
ImportError: No module named ochem_predict_nn.main.transformer
```
I am using Ubuntu 18. 
Do I need to reorganize the files or change some lines of code to get it to work? 

Thanks much!

**Comment by connorcoley** [comment]
Hi @ZZP12 -

You should be able to run all of the code from the ochem_predict_nn if you ensure that the working directory (```'.'```) is in your ```PYTHONPATH``` environment variable. It should just be a matter of running from the right location and having the right path, hopefully no reorganization needed!

**Comment by connorcoley** [comment]
As a follow-up, if you're just getting into the code, you might want to instead take a look at a more recent model that operates quite differently but is faster and more accurate: https://github.com/connorcoley/rexgen_direct
